apiVersion: v1
kind: Service
metadata:
  name: k8sdemo
  namespace: default
  labels:
    app: k8sdemo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30090 #service对外开放端口
  selector:
    app: k8sdemo
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: k8sdemo #名称
  labels:
    app: k8sdemo #标注 
spec:
  replicas: 3 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: k8sdemo
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers: #docker容器的配置
      - name: k8sdemo
        image: 192.168.56.1:5000/k8sdemo/k8s-demo:0.0.2
        imagePullPolicy: IfNotPresent #pull镜像时机，
        ports:
        - containerPort: 8080 #容器对外开放端口
        volumeMounts:
        - name: k8sdemo-logs 
          mountPath: /logs/k8s-demo
      - name: filebeat
        image: 192.168.56.1:5000/docker.elastic.co/beats/filebeat:7.6.2
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        - name: k8sdemo-logs 
          mountPath: /logs/k8s-demo
      volumes:
      - name: k8sdemo-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default

data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /logs/k8s-demo/total.log

      fields:
        app: www
        type: k8sdemo
      fields_under_root: true
      multiline:
        pattern: '^\['
        negate: true
        match: after

    setup.ilm.enabled: false
    setup.template.name: "k8sdemo"
    setup.template.pattern: "k8sdemo-*"

    output.elasticsearch:
      hosts: ['elasticsearch:9200']
      index: "k8sdemo-%{+yyyy.MM.dd}"
